server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.1.178:3306/mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    database: 0
    password:  #redis\u5BC6\u7801
    timeout: 3000ms #redis\u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4
    jedis:
      pool:
        max-active: 8 #\u6700\u5927\u8FDE\u63A5\u6570\uFF0C\u8D1F\u6570\u8868\u793A\u6CA1\u6709\u9650\u5236
        max-wait: -1ms #\u8FDE\u63A5\u6C60\u6700\u5927\u963B\u585E\u7B49\u5F85\u65F6\u95F4\uFF0C\u8D1F\u6570\u8868\u793A\u6CA1\u6709\u9650\u5236
        max-idle: 8 #\u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5927\u7A7A\u95F2\u8FDE\u63A5\u6570
        min-idle: 0 #\u8FDE\u63A5\u6C60\u4E2D\u6700\u5C0F\u8FDE\u63A5\u6570

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

#\u81EA\u5B9A\u4E49redis key\u8BBE\u7F6E
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120 #\u9A8C\u8BC1\u7801\u8D85\u65F6\u65F6\u95F4